version: '3.1'

services:
  php:
    build: .
    image: php:8.1-apache-bullseye
    ports:
      - 8087:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - .:/var/www/html/